languageCode = "de"
title = "Notify Me - Webpages"

DefaultContentLanguage = "de"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Generate QR Codes for Notify Me"

[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"
  [languages.fr]
    weight = 2
    languageName = "Fran√ßais"
  # [languages.it]
  #   weight = 2
  #   languageName = "Italiano"
  [languages.en]
    weight = 4
    languageName = "English"

[markup.goldmark.renderer]
  unsafe= true
